### ISSUE TITLE
Chase Hemphill references *back* in time

### ISSUE THREAD

**Issue by divilian** [TromboneDavies/PolarOps#5]
Add to Zotero whatever looks worth adding.

**Comment by vgcagle** [comment]
Conover- Political Polarization on Twitter 
create a corpus of political communication- a tweet containing at least one politically relevant hashtag 
cluster analysis of retweet and mention networks 
manually annotated users political identity 
retweet and mention networks homogeneous vs heterogeneous content

**Comment by vgcagle** [comment]
Laver- Extracting Policy Positions from Political Texts Using Words as Data 
reference texts with known positions, generate word scores from reference texts, score new text using the word scores

**Comment by vgcagle** [comment]
Lowe- Scaling Policy Preferences from Coded Political Texts 
propose an alternate approach to estimating policy positions based on the logarithm of odds ratios

**Comment by vgcagle** [comment]
Slapin & Proksch -A Scaling Model for Estimating Time-Series Party Positions from Texts 
scaling algorithm called WORDFISH- estimate policy positions based  on word frequencies in text

**Comment by vgcagle** [comment]
Monroe- Fightin' Words: Lexical Feature Selection and Evaluation for Identifying the Content of Political Conflict 
Dirichlet prior
Laplace prior 
p.396-398 political polarization

**Comment by vgcagle** [comment]
Lowe- Understanding Wordscores 
Given R documents or ‘‘reference texts’’ with known positions or scores on a policy dimension, Wordscores attempts to estimate the scores of L out-of-sample documents, the ‘‘virgin
texts.’’ To do so the method first estimates scores for each word type occurring in the reference texts and then combines these wordscores into a score for each virgin document. It is
important to distinguish the two parts: estimating wordscores and estimating document
scores using wordscores because they are, at least in principle, independent parts of the
method. There is usually a third and final part of the method that rescales virgin document
score estimates, so they can be more easily compared with the reference text scores.
